### ISSUE TITLE
igc-pane-header-component css styles are not applied in Edge

### ISSUE THREAD

**Issue by RivaIvanova** [IgniteUI/igniteui-dockmanager#33]
## Description  
Styles for **pane-heade**r and **pane-header active** parts are not applied in Microsoft Edge.

- Microsoft Edge:

![docManager Edge](https://user-images.githubusercontent.com/49126110/176386968-6076aed7-1598-4b13-aec6-f04a9df00412.PNG)

- Chrome/Mozilla Firefox/Opera:

![docManager chrome](https://user-images.githubusercontent.com/49126110/176387201-64ce046c-0427-451e-a0c9-b55005db31b9.PNG)

 * version: 1.8.0
 * browser: Microsoft  Edge

## Steps to reproduce  

1. Apply styling for **pane-header** and **pane-header active** parts.

```scss
// example
igc-dockmanager::part(pane-header) {
  background-color: indigo !important;
  color: white;
}

igc-dockmanager::part(pane-header active) {
  box-shadow: inset 0 -2px 0 0 yellow;
  color: yellow;
}
```
2. Launch the application in Microsoft Edge.

## Result  
Styles are not applied.

## Expected result  
Styles should be applied.
