### ISSUE TITLE
Splitter styles are not applied

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-dockmanager#36]
## Description  
Styles for **splitter**, **splitter-ghost** and **splitter-base** are not applied

 * version: 1.9.0
 * browser: 

## Steps to reproduce  

Apply styling for **splitter**, **splitter-ghost** and **splitter-base** parts.

```scss
// example
igc-dockmanager::part(splitter-ghost) {
  background-color: black;
}

igc-dockmanager::part(splitter-base) {
  background-color: red;
}

igc-dockmanager::part(splitter) {
  margin: 10px;
}
```

## Result  
Styles are not applied.

## Expected result  
Styles should be applied.
